### ISSUE TITLE
"JavaScript error in the main process"

### ISSUE THREAD

**Issue by kingmustard** [aluxian/Messenger-for-Desktop#1178]
Operating system: Windows 10 x64
Messenger for Desktop version: 2.0.4 BETA

When I try to launch the software (I have tried a fresh reinstall), I get:

```
JavaScript error in the main process

RangeError: Maximum call stack size exceeded
    at C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:41:18
    at retrieveSourceMapURL (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:112:14)
    at Array.<anonymous> (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:129:26)
    at C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:43:24
    at mapSourcePosition (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:159:21)
    at wrapCallSite (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:330:20)
    at C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:365:26
    at Array.map (native)
    at Function.prepareStackTrace (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\node_modules\source-map-support\source-map-support.js:364:24)
    at RangeError.get stack [as stack] (native)
    at C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\common\utils\logger.js:107:53
    at ensureDataLoaded (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\browser\utils\prefs.js:43:9)
    at Object.get (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\browser\utils\prefs.js:87:3)
    at send (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\browser\services\piwik.js:15:40)
    at reportToPiwik (C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\common\utils\logger.js:47:11)
    at C:\Users\abc\AppData\Local\messengerfordesktop\app-2.0.4\resources\app.asar\scripts\common\utils\logger.js:110:7

**Comment by Sytten** [comment]
Duplicate https://github.com/aluxian/Messenger-for-Desktop/issues/1170
