### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by kiwinet** [aluxian/Messenger-for-Desktop#1248]
* Ubuntu 16.10 amd64 / Gnome 3.
* Messenger for Desktop version: 2.0.8 deb and build on system

When try to start messanger, got error:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.GHpDDI: failed to map segment from shared object
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

**Comment by aluxian** [comment]
Please update to 2.0.9 and reopen if this is still a problem.
