### ISSUE TITLE
White screen on v2.0.9

### ISSUE THREAD

**Issue by carc1n0gen** [aluxian/Messenger-for-Desktop#1327]
* Operating system: macOS High Sierra
* Messenger for Desktop version: v2.0.9

I was using the app perfectly fine for about a month and then today when I launched the app I was stuck at a white blank screen.  I tried reinstalling the latest version with no luck

<img width="851" alt="screen shot 2017-11-14 at 9 34 23 am" src="https://user-images.githubusercontent.com/8248986/32785785-60c161f4-c920-11e7-9bc9-e75ff845a364.png">

```
DEBUG [2017-11-14 14:42:55.637] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:main cli args parsed {"_":[],"os-startup":false,"osStartup":false,"portable":false,"debug":true,"console-logs":false,"consoleLogs":false,"repl":false,"mas":false,"version":false,"v":false,"squirrel-install":false,"squirrelInstall":false,"squirrel-uninstall":false,"squirrelUninstall":false,"squirrel-updated":false,"squirrelUpdated":false,"squirrel-obsolete":false,"squirrelObsolete":false,"squirrel-firstrun":false,"squirrelFirstrun":false,"help":false,"h":false,"repl-port":3499,"replPort":3499,"$0":"Applications/Messenger for Desktop.app/Contents/MacOS/Messenger for Desktop --debug"}
DEBUG [2017-11-14 14:42:55.641] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:main running in debug mode
DEBUG [2017-11-14 14:42:55.645] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:utils:prefs prefs data restored
DEBUG [2017-11-14 14:42:55.717] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:main ready
DEBUG [2017-11-14 14:42:55.718] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:main intercepting protocol http
DEBUG [2017-11-14 14:42:55.730] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:main launching app
DEBUG [2017-11-14 14:42:55.861] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:managers:main-window-manager creating main window
DEBUG [2017-11-14 14:42:55.942] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:managers:auto-update-manager starting auto updater
DEBUG [2017-11-14 14:42:55.942] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:managers:auto-update-manager updater feed url: https://updates.messengerfordesktop.com/update/stable/darwin?version=2.0.6
DEBUG [2017-11-14 14:42:55.948] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:managers:auto-update-manager scheduling update checks every 14400000 ms
DEBUG [2017-11-14 14:42:55.949] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:browser:managers:auto-update-manager checking for update...
DEBUG [2017-11-14 14:42:55.992] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:common:utils:files:browser dictionaries in /Applications/Messenger for Desktop.app/Contents/Resources/app.asar/dicts found: ["de","es","fr","ro_RO","ru"]
DEBUG [2017-11-14 14:42:55.992] Tue, 14 Nov 2017 14:42:55 GMT messengerfordesktop:common:utils:files:browser dictionaries in /Applications/Messenger for Desktop.app/Contents/Resources/app.asar/node_modules/spellchecker/vendor/hunspell_dictionaries found: ["en_US"]
DEBUG [2017-11-14 14:42:56.009] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-menu-manager app menu created
DEBUG [2017-11-14 14:42:56.012] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-menu-manager app menu set
DEBUG [2017-11-14 14:42:56.343] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-menu-manager auto updater on: checking-for-update params:
DEBUG [2017-11-14 14:42:56.349] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-menu-manager auto updater on: update-available params:
DEBUG [2017-11-14 14:42:56.360] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:main intercepted http GET http://app.messengerfordesktop.com/html/app.html => file://<app>/html/app.html
DEBUG [2017-11-14 14:42:56.455] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:main intercepted http GET http://app.messengerfordesktop.com/styles/app.css => file://<app>/styles/app.css
DEBUG [2017-11-14 14:42:56.455] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:main intercepted http GET http://app.messengerfordesktop.com/styles/loader.css => file://<app>/styles/loader.css
DEBUG [2017-11-14 14:42:56.455] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:main intercepted http GET http://app.messengerfordesktop.com/scripts/renderer/index.js => file://<app>/scripts/renderer/index.js
DEBUG [2017-11-14 14:42:56.491] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:renderer:webview:index loading https://www.messenger.com/login
DEBUG [2017-11-14 14:42:56.534] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:renderer:services:piwik setting up piwik
DEBUG [2017-11-14 14:42:56.658] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:renderer:components:keymap binding keyboard shortcuts
DEBUG [2017-11-14 14:42:56.686] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:renderer:webview:listeners document DOMContentLoaded
DEBUG [2017-11-14 14:42:56.695] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-window-manager ready-to-show
DEBUG [2017-11-14 14:42:56.793] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-window-manager onFocus
DEBUG [2017-11-14 14:42:56.803] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:browser:managers:main-window-manager onShow
DEBUG [2017-11-14 14:42:56.885] Tue, 14 Nov 2017 14:42:56 GMT messengerfordesktop:renderer:services:piwik piwik analytics instance created
DEBUG [2017-11-14 14:42:57.718] Tue, 14 Nov 2017 14:42:57 GMT messengerfordesktop:renderer:preload:notification extending HTML5 Notification
DEBUG [2017-11-14 14:42:57.722] Tue, 14 Nov 2017 14:42:57 GMT messengerfordesktop:renderer:webview:listeners webview dom-ready
DEBUG [2017-11-14 14:42:57.724] Tue, 14 Nov 2017 14:42:57 GMT messengerfordesktop:renderer:webview:listeners restoring theme default
DEBUG [2017-11-14 14:42:57.727] Tue, 14 Nov 2017 14:42:57 GMT messengerfordesktop:renderer:webview:listeners restoring webview css override default
FATAL [2017-11-14 14:42:57.731]   messengerfordesktop:browser:utils:prefs: Error: default value for key notify-app-updated is undefined
    at Object.get (/Applications/Messenger for Desktop.app/Contents/Resources/app.asar/scripts/browser/utils/prefs.js:88:16)
    at callFunction (/Applications/Messenger for Desktop.app/Contents/Resources/electron.asar/browser/rpc-server.js:227:18)
    at EventEmitter.<anonymous> (/Applications/Messenger for Desktop.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Messenger for Desktop.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
DEBUG [2017-11-14 14:42:57.732] Tue, 14 Nov 2017 14:42:57 GMT messengerfordesktop:renderer:webview:listeners webview did-finish-load
DEBUG [2017-11-14 14:43:01.331] Tue, 14 Nov 2017 14:43:01 GMT messengerfordesktop:browser:menus:expressions:expr-click opening log file with default app /Users/evansca/Library/Application Support/Messenger for Desktop/logs/1510670575638.txt

```

**Comment by mciszczon** [comment]
Same here on Windows 10.

**Comment by kimusan** [comment]
Same on win7. Works fine on Ubuntu Linux
