### ISSUE TITLE
A JavaScript error occurred in the main process Uncaught Exception:

### ISSUE THREAD

**Issue by abdiprawira** [aluxian/Messenger-for-Desktop#1344]
help me please

`[abdi@Eldersc0deFamily]:~# messengerfordesktop

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.laShiL: failed to map segment from shared object
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)`

**Comment by Dominik-H** [comment]
@cement-head This is a different issue completely not related to this one I already created a new one: #1346
