### ISSUE TITLE
JavaScript error in the main process

### ISSUE THREAD

**Issue by Dominik-H** [aluxian/Messenger-for-Desktop#1346]
* Operating system: Ubuntu 17.10
* Messenger for Desktop version: v2.0.9-stable

**Everytime I click on Check for Update from Menu AND/OR on program startup (when the thing happens automatically) AND/OR every few hours (I don't know the exact interval) again when the program checks for updates automatically I get this error:**

```
TypeError: Invalid Version: undefined
    at new SemVer (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:279:11)
    at compare (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:595:10)
    at /opt/messengerfordesktop/resources/app.asar/scripts/browser/components/auto-updater/base.js:79:49
    at done (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:432:14)
    at PassThrough.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:671:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Attached logs from Debug Mode:**
[1521993855419.txt](https://github.com/aluxian/Messenger-for-Desktop/files/1845494/1521993855419.txt)

**Comment by cement-head** [comment]
okay, must be a change in FB Messenger API

**Comment by RKCZ** [comment]
The same issue on Win10 (64bit) v2.0.9

**Comment by pyraohms** [comment]
Same issue on system:

Linux 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DarkSir23** [comment]
Also on Linux Mint 18.3

**Comment by nithwith** [comment]
![image](https://user-images.githubusercontent.com/19471913/38088933-fc96f6dc-335d-11e8-9610-2cb32db8534a.png)

I'm on ubuntu 16.04, did you think it's the same error ?

**Comment by BarsaTM** [comment]
@nithwith yeap! It's the same.

**Comment by yerbestpal** [comment]
Same here, Kubuntu 17.10
```
TypeError: Invalid Version: undefined
    at new SemVer (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:279:11)
    at compare (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:595:10)
    at /opt/messengerfordesktop/resources/app.asar/scripts/browser/components/auto-updater/base.js:79:49
    at done (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:432:14)
    at PassThrough.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:671:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by gadomsky** [comment]
same here :) ubuntu 17.10

**Comment by m3rgus** [comment]
Got that error as well.

Messenger for Desktop v2.0.9-stable

Kubuntu 16.04 (4.13.0-37-generic)

Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Error does not appear after disabling automatic updates.

**Comment by jeconiassantos** [comment]
Same here. Mint 18.1

**Comment by linuxlite** [comment]
Happening here on Linux Lite 3.8 too:

``TypeError: Invalid Version: undefined
    at new SemVer (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:279:11)
    at compare (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/opt/messengerfordesktop/resources/app.asar/node_modules/semver/semver.js:595:10)
    at /opt/messengerfordesktop/resources/app.asar/scripts/browser/components/auto-updater/base.js:79:49
    at done (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:432:14)
    at PassThrough.<anonymous> (/opt/messengerfordesktop/resources/app.asar/node_modules/needle/lib/needle.js:671:11)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)``

**Comment by linuxlite** [comment]
No dev in nearly a year. App looks to be abandoned. Last commit was - May 16, 2017

**Comment by mickael83** [comment]
The error disappears disabling the option "check for update automaticaly" in the app menu.

**Comment by PeterDobrinov** [comment]
Same here, Debian 9 with kde.

**Comment by Martina-Neumayer** [comment]
Just update your both java and the nodejs to the latest possible versions and the issue is gone ;)

**Comment by Martina-Neumayer** [comment]
I've updated mine (besides also a few other affected by this issue systems too) and check this out..
The error "magicaly" dissapeared ;) 
Locked to the old ones? hahaha.. who is locked? Especially the linux users are locked not.

**Comment by SolarLiner** [comment]
https://github.com/sindresorhus/caprine is another desktop wrapper for Messenger. There is no point in having two different projects for the same thing.

**Comment by Martina-Neumayer** [comment]
They are meny to be honest ;)

**Comment by TehTotalPwnage** [comment]
I wouldn't necessarily get my hopes up on this repository updating anytime soon. This repository's owner is still active on GitHub but has basically neglected to touch this repository in what is coming up on a year now. Additionally, if you look at other issues like #1153, this project has other issues as well, like the owner of the repository reportedly transferring the original domain name for this project to an owner who has been [bundling malware into the installers.](https://messengerfordesktop.com)

At this point, I'd just recommend using Caprine, as @SolarLiner mentioned. All the other forks for this project appear to have died off, and even @Sytten, who runs the [newer and malware-free site](https://messengerfordesktop.org) has considered doing so in the discussion for #1343.
