### ISSUE TITLE
v2.0.0-beta fails to launch on Arch Linux: JavaScript Error

### ISSUE THREAD

**Issue by fusion809** [aluxian/Messenger-for-Desktop#525]
Hi,

I've created this PKGBUILD for messengerfordesktop, via editing the PKGBUILD in the AUR:

``` bash
# Maintainer:  Marcin Wieczorek <marcin@marcin.co>
# Contributor: Michael Corrigan <ghost.vonage AT gmail DOT com>
# Contributor: tomsik68 <tomsik68 AT gmail DOT com>
# Contributor: gandl <gandlspam AT gmail DOT com>
# Contributor: Jristz <prflr88 AT gmail DOT com>

pkgname=messengerfordesktop
pkgver=2.0.0
pkgrel=1
pkgdesc="Beautiful desktop client for Facebook Messenger."
arch=('i686' 'x86_64')
url="http://messengerfordesktop.com/"
license=('MIT')
conflicts=('messengerfordesktop-git' 'messengerfordesktop-bin')
options=(!strip)
depends=('libxtst' 'alsa-lib' 'gtk2' 'gconf' 'libnotify' 'nss' 'xorg-xprop' 'xorg-xwininfo')
makedepends=('gulp' 'npm')
source=("https://github.com/Aluxian/Facebook-Messenger-Desktop/archive/v${pkgver/_/-}.tar.gz"
        "start.sh")

md5sums=('320d71dff87d14772c8c8bfe7ec80b7a'
         '31abbecf99328b1b77ee1bdb1e2d981f')

if [ $CARCH == x86_64 ]; then
  _arch="64"
else
  _arch="32"
fi

build() {
  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}"
  npm install
  gulp build:linux${_arch}
}

package() {
    BUILDS="build/linux${_arch}/usr/share/"

  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}/build/linux${_arch}"
  for file in `find . -type f`; do
        install -D -m644 "${file}" "${pkgdir}/${file}"
  done;

  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}/"
  install -D -m644 "$BUILDS/applications/messengerfordesktop.desktop"           "${pkgdir}/usr/share/applications/messengerfordesktop.desktop"
  install -D -m644 "$BUILDS/icons/hicolor/512x512/apps/messengerfordesktop.png" "${pkgdir}/usr/share/pixmaps/messengerfordesktop.png"
  install -D -m644 "LICENSE.md"                                                                     "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.md"
    chmod 755 "${pkgdir}/opt/messengerfordesktop/messengerfordesktop"
    chmod 755 "${pkgdir}/opt/messengerfordesktop/libnode.so"
}
```

I built a package with it, tried to launch Messenger via running `/opt/messengerfordesktop/messengerfordesktop` and it returned the error message:

``` bash
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'source-map-support'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/opt/messengerfordesktop/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/messengerfordesktop/resources/app/scripts/browser/init.js:1:114)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

As, I copied the contents of the `build/linux64/` output directory across into the `$pkgdir` directory, without much modification I suspect this is not a packaging issue but an issue with this upstream project. Running `build/linux64/opt/messengerfordesktop/messengerfordesktop` returns the same error, so this definitely seems like an error with the build of Messenger. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
After reading the README on the `develop` branch I adjusted my PKGBUILD to:

```bash
# Maintainer:  Marcin Wieczorek <marcin@marcin.co>
# Contributor: Michael Corrigan <ghost.vonage AT gmail DOT com>
# Contributor: tomsik68	<tomsik68 AT gmail DOT com>
# Contributor: gandl <gandlspam AT gmail DOT com>
# Contributor: Jristz <prflr88 AT gmail DOT com>

pkgname=messengerfordesktop
pkgver=2.0.0
pkgrel=1
pkgdesc="Beautiful desktop client for Facebook Messenger."
arch=('i686' 'x86_64')
url="http://messengerfordesktop.com/"
license=('MIT')
conflicts=('messengerfordesktop-git' 'messengerfordesktop-bin')
options=(!strip)
depends=('libxtst' 'alsa-lib' 'gtk2' 'gconf' 'libnotify' 'nss' 'xorg-xprop' 'xorg-xwininfo')
makedepends=('gulp' 'npm')
source=("https://github.com/Aluxian/Facebook-Messenger-Desktop/archive/v${pkgver/_/-}.tar.gz"
		"start.sh")

md5sums=('320d71dff87d14772c8c8bfe7ec80b7a'
         '31abbecf99328b1b77ee1bdb1e2d981f')

if [ $CARCH == x86_64 ]; then
  _arch="64"
else
  _arch="32"
fi

build() {
  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}"
  npm install
	cd src
	npm install
	cd -
  gulp rebuild:64
  gulp build:linux${_arch} --prod
}

package() {
	BUILDS="build/linux${_arch}/usr/share/"

  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}/build/linux${_arch}"
  for file in `find . -type f`; do
		install -D -m644 "${file}" "${pkgdir}/${file}"
  done;

  cd "${srcdir}/Facebook-Messenger-Desktop-${pkgver/_/-}/"
  install -D -m644 "$BUILDS/applications/messengerfordesktop.desktop" 	        "${pkgdir}/usr/share/applications/messengerfordesktop.desktop"
  install -D -m644 "$BUILDS/icons/hicolor/512x512/apps/messengerfordesktop.png" "${pkgdir}/usr/share/pixmaps/messengerfordesktop.png"
  install -D -m644 "LICENSE.md" 								                            		"${pkgdir}/usr/share/licenses/${pkgname}/LICENSE.md"
	chmod 755 "${pkgdir}/opt/messengerfordesktop/messengerfordesktop"
	chmod 755 "${pkgdir}/opt/messengerfordesktop/libnode.so"
}
```

but it still failed to build a functional package.

**Comment by Sytten** [comment]
Good thanks for reporting!
@Aluxian

**Comment by aluxian** [comment]
Is this still an issue? I think MFD is already in AUR now.
