### ISSUE TITLE
Not working behind enterprise proxy

### ISSUE THREAD

**Issue by vallovic** [Aluxian/Messenger-for-Desktop#536]
Didn't had this problem with versions 1.4.X but starting with version 1.5.0-beta.X (and now the current beta version 2.0 too) the problem appeared.

At work, like many people, I have to use a proxy to connect to the Internet. When I run the app it just hangs on the white window with the blue loader, going nowhere.

This is the console log when I run it from there:
`
ERROR [2016-08-30 13:30:49.933]   messengerfordesktop:browser/managers/auto-update-manager: Error: connect ECONNREFUSED 104.24.109.166:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1080:14)
[1570:0830/143105:FATAL:url_request_context.cc(104)] Check failed: false. Leaked 1 URLRequest(s). First URL: http://pcprt4prxscr.telecom.pt/proxyPTP.pac.
#0 0x000001e095ae <unknown>
#1 0x000001e1f1bb <unknown>
#2 0x0000009646bb <unknown>
#3 0x0000009644f6 <unknown>
#4 0x0000009646e9 <unknown>
#5 0x0000034da2ad brightray::URLRequestContextGetter::~URLRequestContextGetter()
#6 0x0000034da409 brightray::URLRequestContextGetter::~URLRequestContextGetter()
#7 0x0000009650d7 <unknown>
#8 0x000003409a11 _ZN4base8internal9BindStateINS0_15RunnableAdapterIPFv13scoped_refptrIN9brightray23URLRequestContextGetterEEEEES7_JRS6_EE7DestroyEPNS0_13BindStateBaseE
#9 0x000001e34e5d <unknown>
#10 0x000001e25c71 <unknown>
#11 0x000001dfe9d9 <unknown>
#12 0x000001e3e03e <unknown>
#13 0x000001e24c7a <unknown>
#14 0x00000266c4d6 <unknown>
#15 0x00000266c6de <unknown>
#16 0x000001e5d708 <unknown>
#17 0x000001e59c93 <unknown>
#18 0x7f86234516fa start_thread
#19 0x7f861cedfb5d clone

`

And this is the log when I use the option to restart in debug mode and then open the log:
http://pastebin.com/v4ThQD77

I think it's not using the PAC file I have defined as system-wide proxy configuration. As an example, [Ghetto Skype](https://github.com/stanfieldr/ghetto-skype) (which uses Electron) sets the proxy when it starts (don't know what they're doing behind the scenes, it's just a message that appears when I run it) and it's working flawlessly.

**Comment by Sytten** [comment]
We will take a look at that. Thanks!
@Aluxian

**Comment by vallovic** [comment]
Is there any way to ignore system-wide proxy configuration? I need to use a PAC file to access my enterprise proxy and I still can't connect using version 2 due to the same error but with other apps I can use proxychains to bypass the proxy (p.e., I use it with Corebird). When I try Messenger-for-Desktop with proxychains it hangs and when I kill the process this is the message (_PAC URL edited_):

```
ERROR [2017-01-19 15:11:19.917]   messengerfordesktop:browser/managers/auto-update-manager: Error: connect ECONNREFUSED 104.24.108.166:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
^C[7721:0119/151125:FATAL:url_request_context.cc(108)] Check failed: false. Leaked 1 URLRequest(s). First URL: http://[URL]/proxy.pac.
#0 0x000001e5801e <unknown>
#1 0x000001e6dd1b <unknown>
#2 0x0000009814eb <unknown>
#3 0x000000981526 <unknown>
#4 0x0000035c364d brightray::URLRequestContextGetter::~URLRequestContextGetter()
#5 0x0000035c37a9 brightray::URLRequestContextGetter::~URLRequestContextGetter()
#6 0x000000981fb7 <unknown>
#7 0x0000034e0391 _ZN4base8internal9BindStateINS0_15RunnableAdapterIPFv13scoped_refptrIN9brightray23URLRequestContextGetterEEEEEJRS6_EE7DestroyEPNS0_13BindStateBaseE
#8 0x000001e83bfd <unknown>
#9 0x000001e74a01 <unknown>
#10 0x000001e4e129 <unknown>
#11 0x000001e8cede <unknown>
#12 0x000001eabeca <unknown>
#13 0x0000027078f6 <unknown>
#14 0x000002707afe <unknown>
#15 0x000001eabf8e <unknown>
#16 0x000001ea8513 <unknown>
#17 0x7f82fd7a56ba start_thread
#18 0x7f82f723382d clone

[1]    7721 abort      messengerfordesktop
```
If I could disable Messenger-for-Desktop from going to check system-wide proxy settings, maybe I could get it through.

Until then, I'll have to keep using 1.4 version

**Comment by Aluxian** [comment]
Hey,

MFD works like Chromium. So how would you make Chrome/Chromium bypass the proxy?

**Comment by vallovic** [comment]
Well, maybe not using proxychains since I can't use it with Chromium too, but installing a proxy extension in Chromium (like FoxyProxy) I can easily define my SOCKS proxy and navigate using it. Just an example.

But as I said in the first post, I use Ghetto Skype (which is developed with Electron) and it reads the PAC file from the system-wide settings too and run it flawlessly, so they must be doing something else. Note that I can open messenger.com and web.skype.com within the browser without any trouble (without using my SOCKS proxy).

**Comment by vallovic** [comment]
Just checked out and I wasn't remembering it, but **I'm using MFD v1.5.0-beta.1 using proxychains**.

Some shared images/videos in the chat were blocked due to coming from Facebook (which is blocked, messenger.com isn't) so I started using MFD with proxychains and it works. So, maybe something with Electron?

**Comment by Aluxian** [comment]
Sorry, I'm confused now as to what works and what doesn't. MFD v2+ is built on Electron.

**Comment by vallovic** [comment]
MFD **v1.5.0-beta.1**: I think it is build using NWJS and I can use it behind the enterprise proxy for normal chatting (I just use it with proxychains, without any problem, because that way I can see everything in the chat - videos/images from FB, videos from Youtube,...)

MFD **v2+**: I can't use it, even for normal chatting, because it hangs due to the PAC file I have applied system-wide. Ghetto Skype, which is built using Electron too, just works flawlessly and reads the system-wide proxy settings (therefore, handles the PAC file correctly).

**Comment by Aluxian** [comment]
Alright! I'll see what I can do.
