### ISSUE TITLE
JavaScript error in the main process

### ISSUE THREAD

**Issue by aluxian-huginn** [Aluxian/Messenger-for-Desktop#576]
**Description:**
JavaScript error in the main process

**Steps to reproduce:**
right click on main window canvas

**App version:**
2.0.1-beta

**OS:**
Windows 10 home

**Works in WhatsApp Web:**

**Extra:**
[Not answered]

**Comment by Cuchulain** [comment]
```
[Content]
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\cuchu\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\renderer\preload\listeners.js:16:42.
    at WebContents.callIntoRenderer (C:\Users\cuchu\AppData\Local\messengerfordesktop\app-2.0.1\resources\electron.asar\browser\rpc-server.js:189:19)
    at emitTwo (events.js:111:20)
    at WebContents.emit (events.js:191:7)
```
