### ISSUE TITLE
Crash/Java issue upon startup.

### ISSUE THREAD

**Issue by Lemagex** [aluxian/Messenger-for-Desktop#613]
**Description:**
Messenger crashes when started, for some reason it has updated to beta despite the update channel being "Stable" ever since, when started, it comes up with this message.

[Window Title]
Error

[Main Instruction]
JavaScript error in the main process

[Content]
RangeError: Maximum call stack size exceeded
    at CallSiteToString [as toString](C:UserslemagAppDataLocalmessengerfordesktopapp-2.0.1resourcesapp.asarnode_modulessource-map-supportsource-map-support.js:239:12)
    at C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\node_modules\source-map-support\source-map-support.js:362:24
    at Array.map (native)
    at Function.prepareStackTrace (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\node_modules\source-map-support\source-map-support.js:361:24)
    at SyntaxError.get stack [as stack](native)
    at C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\common\utils\logger.js:107:53
    at ensureDataLoaded (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\utils\prefs.js:43:9)
    at Object.get (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\utils\prefs.js:87:3)
    at send (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\services\piwik.js:15:40)
    at reportToPiwik (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\common\utils\logger.js:47:11)
    at C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\common\utils\logger.js:110:7
    at ensureDataLoaded (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\utils\prefs.js:43:9)
    at Object.get (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\utils\prefs.js:87:3)
    at send (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\browser\services\piwik.js:15:40)
    at reportToPiwik (C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\common\utils\logger.js:47:11)
    at C:\Users\lemag\AppData\Local\messengerfordesktop\app-2.0.1\resources\app.asar\scripts\common\utils\logger.js:110:7

[OK]

**Steps to reproduce:**
Start up application.

**App version:**
2.0.1 despite not selecting beta.

**OS:**
Windows 10 Home x64

**Extra:**
This issue has been reproduced on three of my systems.
Attempted to reinstall via uninstaller and deleting the Appdata messengerfordesktop directory, attempted to download new installer (Stable and Beta) still no good.

**Comment by pancur** [comment]
Exactly same here

**Comment by gabrhel** [comment]
+1

**Comment by remustata** [comment]
I also have the same error, can someone suggest a fix for it? Reinstalling does not work

**Comment by Dave94** [comment]
I have this problem too :(

**Comment by tigereyes7088** [comment]
I have the same problem too! and I really loved having this. What can I do to fix it? I've uninstalled and reinstalled as well and still no Joy. Has anyone gotten any answers or feedback?

**Comment by remustata** [comment]
I eventually fixed it by deleting everything that has to do with the software. To find all the files that are spread in the system in various places I used another powerful search software called "Everything" https://www.voidtools.com/.
After this a clean reinstall fixed it.

**Comment by aluxian** [comment]
I think I know how to fix it, will do so in the next update.

**Comment by tigereyes7088** [comment]
I installed the update as suggested but I am still getting that Java error.

**Comment by tigereyes7088** [comment]
Remus, can I ask what you put in the search options on the program you suggested? I'm not good when it comes to the things it's asking for. Thanks in advance.


________________________________

**Comment by aluxian** [comment]
Hey everyone, please check the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases
